package ru.skypro.zveropolis.relocation;

public enum StateBot {
    START_MENU, CAT_MENU, DOG_MENU, REPORT_CAT_MENU, REPORT_DOG_MENU, CALL_VOLUNTEER_MENU, INFO_CAT_SHELTER_MENU, INFO_DOG_SHELTER_MENU
}
